name: main
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  mongo_dart: ^0.7.4
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
